### PR TITLE
add method for Distributions.rand(::ResettableRNG, ::Binomial)

### PR DESCRIPTION
**Pull request by slwu89**
This should address #248, which actually didn't have anything to do with product measure, but rather a method for the Binomial distribution. Also added a test to check for this behavior; it would fail previously.

### CODE REVIEW

**Comment by cscherrer** [comment]
Hi @slwu89 , looks like I have some catching up to do:
1. Welcome!
2. Sorry I had missed your #248 
3. Thank you for the PR!!

I like the simplicity of your approach, but it specializes for `Binomial`, which shouldn't need to be the case. In this code
```julia
function Dists.rand(rng::ResettableRNG, d::Dists.Binomial)
    rand(rng.rng, d)
end
```

we'd usually instead write
```julia
function Dists.rand(rng::ResettableRNG, ::Type{T}, d::Dists.Binomial) where {T}
    rand(rng.rng, T, d)
end
```

The idea is that the `T` is propagated down to the low-level code, where it ends up calling `rand(T)`, `randexp(T)`, or `randn(T)`. This works well in most cases, but for `ResettableRNG`s it's currently broken. I think at some point it's dispatching incorrectly. I'll have a look over the weekend; I'm guessing it can be a quick fix.

**Comment by cscherrer** [comment]
Hi @slwu89 , I think I got the dispatch problems fixed. Here's your MWE now (using Julia 1.9, because that's just what I have loaded)
```julia
julia> using Random

julia> using MeasureTheory

julia> rng = ResettableRNG(Random.Xoshiro(), 6542022242862247233)
ResettableRNG(::Xoshiro, 6542022242862247233)

julia> mu = ProductMeasure([Binomial(n = 990, p = 0.00995017), Binomial(n = 10, p = 0.0246901)])
ProductMeasure([Binomial(n = 990, p = 0.00995017), Binomial(n = 10, p = 0.0246901)])

julia> rand(rng, mu)
2-element Vector{Int64}:
 12
  1
```

**Comment by cscherrer** [comment]
I think this is ready to go once tests pass. Thanks for catching this and starting on the fix! I changed the solution, but it was very helpful to have the test you added to make sure things are working properly.

**Comment by slwu89** [comment]
Thanks @cscherrer! Great to see the "official" solution too, helps me understand better the design of the package.

**Pull request merged**
