### PR TITLE
Set up clean documentation

### PR DESCRIPTION
**Pull request by gdalle**
- Integrate MeasureBase docstrings into the MeasureTheory docs
- Clean up README

### CODE REVIEW

**Comment by jeremiahpslewis** [comment]
@gdalle hey! quick question, this looks like an awesome PR giving the docs a round of polish. Would you entertain / be interested in a second reader?

**Comment by gdalle** [comment]
@jeremiahpslewis yes sure, knock yourself out! However my goal for the afternoon is to try and understand the package as a whole by adding docstrings wherever I can, so the docs will probably change a lot in the process.

**Comment by gdalle** [comment]
In a nutshell, what I've done sofar is basically just a lot of reorganizing, but I plan to add more content

**Comment by jeremiahpslewis** [comment]
Cool! Wanted to do the same (better understand the package) by going through your PR. Do you want to ping me when you've reached a steady state and I'll go through it?

**Comment by gdalle** [comment]
Sure!

**Comment by cscherrer** [comment]
@jeremiahpslewis I think we can get these into master and review there before a release, it's easier than building them locally. Also, are you in the MeasureTheory Zulip?

**Review by cscherrer — APPROVED** [review]

**Comment by jeremiahpslewis** [comment]
No, how do I join?

**Comment by cscherrer** [comment]
https://discourse.julialang.org/t/come-join-the-julia-zulip-chat/36070

**Pull request merged**
